export const Images = {
    favicon: "/assets/my-logo.jpg",
    cebuana: "/assets/cebuana-logo.png",
    okada: "/assets/okada-logo.png",
    xffiliate: "/assets/xffiliate-logo.png",
    gpa: "/assets/gpa-logo.jpg",
    cover: "/assets/side-view.jpg",
    zuitt: "/assets/zuitt.png",
    zuitt2: "/assets/desk-angle.jpg",
    xtendly: "/assets/xtendly.webp",
    xtendly2: "/assets/xtendly2.jpg",
    vontos: "/assets/vontos.webp",
    prosperna: "/assets/prosperna.png",
    college: "/assets/college.jpg",
    journey: "/assets/journey.png",
    journey2: "/assets/journey2.png",
    math: "/assets/bg-math.jpg",
    desktopMobile: "/assets/bg-desktop-mobile.jpg",
    website: "/assets/bg-website.png",
    website2: "/assets/bg-website2.jpg",
    native: "/assets/native.webp",
    nextjs: "/assets/nextjs.png",
    nodejs: "/assets/nodejs.jpg",
    reactjs: "/assets/reactjs.webp",
    flutter: "/assets/flutter.png",
    development: "/assets/development.jpg",
    technical: "/assets/technical.jpg",
    otherSkills: "/assets/otherSkills.jpg",
    formal1: "assets/formal1.jpg",
    formal2: "assets/formal2.jpg",
    formal3: "assets/formal3.jpg",
    formal4: "assets/formal4.jpg",
    formal5: "assets/formal5.jpg",
    formal5b: "assets/formal5b.png",
    gmeet: "assets/gmeet.jpg",
    deskMail: "assets/deskMail.jpg",
    deskAngle2: "assets/desk-angle2.jpg",
    seoServices: "/assets/seo-bg-services.png",
    market: "assets/market.jpg",
    xtendlyLogo: "assets/xtendly_logo.webp",
    linkedInLogo: "assets/linkedin-logo.png",
    gitlabLogo: "assets/gitlab-logo.png",
    githubLogo: "assets/github-logo.png",
    facebookLogo: "assets/facebook-logo.png",
    twitterLogo: "assets/twitter-logo.png",
    zuittLogo: "assets/logo-zuitt.png",
}

export const ImageUrl = {
    cover: "https://my-assets-indol.vercel.app/assets/cover.png",
}

export const Icons = {
    postman: "/assets/logo-postman.png",
    vscode: "/assets/logo-vscode.png",
    bootstrap: "/assets/logo-bootstrap.png",
    react: "/assets/logo-react.png",
    firebase: "/assets/logo-firebase.webp",
    gcp: "/assets/logo-gcp.png",
    appstore: "/assets/logo-appstore.png",
    xcode: "/assets/logo-xcode.png",
    dart: "/assets/logo-dart.png",
    flutter: "/assets/logo-flutter.png",
    restapi: "/assets/logo-rest.png",
    tailwind: "/assets/logo-tailwind.png",
    next: "/assets/logo-next.png",
    node: "/assets/logo-nodejs.png",
    javascript: "/assets/logo-javascript.png",
    html: "/assets/logo-html5.png",
    css: "/assets/logo-css3.png",
    mongodb: "/assets/logo-mongodb.png",
    sublime: "/assets/logo-sublime-text-3.png",
    git: "/assets/logo-git.png",
    //postMan: "/assets/logo.png",
}