export const Images = {
    favicon: "/assets/my-logo.jpg",
    cebuana: "/assets/cebuana-logo.png",
    okada: "/assets/okada-logo.png",
    xffiliate: "/assets/xffiliate-logo.png",
    gpa: "/assets/gpa-logo.jpg",
    cover: "/assets/side-view.jpg",
    zuitt: "/assets/zuitt.png",
    zuitt2: "/assets/desk-angle.jpg",
    xtendly: "/assets/xtendly.webp",
    xtendly2: "/assets/xtendly2.jpg",
    vontos: "/assets/vontos.webp",
    prosperna: "/assets/prosperna.png",
    college: "/assets/college.jpg",
    journey: "/assets/journey.png",
    journey2: "/assets/journey2.png",
    math: "/assets/bg-math.jpg",
    desktopMobile: "/assets/bg-desktop-mobile.jpg",
    website: "/assets/bg-website.png",
    website2: "/assets/bg-website2.jpg",
}